apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: s3fs-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: s3fs-app
    spec:
      containers:
      - name: s3fs-app
        image: kubernetesio/s3fs
        ports:
        - containerPort: 22
        env:
        - name: SFTP_USER
          valueFrom:
            secretKeyRef:
              name: s3fs-secret
              key: sftp_user
        - name: SFTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: s3fs-secret
              key: sftp_password
        - name: AWS_ACCESSKEY
          valueFrom:
            secretKeyRef:
              name: s3fs-secret
              key: aws_accesskey
        - name: AWS_SECRETKEY
          valueFrom:
            secretKeyRef:
              name: s3fs-secret
              key: aws_secretkey
        - name: S3_BUCKET
          value: aws.amazon.com
        - name: S3_KEY
          value: /
        - name: SSH_KEY
          valueFrom:
            secretKeyRef:
              name: s3fs-secret
              key: ssh_key
---
apiVersion: v1
kind: Service
metadata:
  name: s3fs-svc
spec:
  ports:
  - port: 22
    targetPort: 22
    protocol: TCP
  type: LoadBalancer
  selector:
    k8s-app: s3fs-app
